In [57]:
import sqlite3
from pandas.io import sql
import subprocess
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [58]:
from dotenv import load_dotenv
import os
from sqlalchemy import create_engine
import pandas as pd
# Load environment variables from the .env file
load_dotenv()

# Retrieve the database credentials from environment variables
db_username = os.getenv("DB_USERNAME")
db_password = os.getenv("DB_PASSWORD")
db_host = os.getenv("DB_HOST")
db_port = os.getenv("DB_PORT")
db_name = os.getenv("DB_NAME")

# Use the credentials in your database connection code
connection_string = f"postgresql://{db_username}:{db_password}@{db_host}:{db_port}/{db_name}"
# ... rest of your code ...
engine = create_engine(connection_string)

engine = create_engine(os.environ["DATABASE_URL"])

In [62]:
%%sql postgresql://{db_username}:{db_password}@{db_host}:{db_port}/{db_name}

-- Ranking the most polluted cities by year and season (spring)
SELECT
    SUM(AQI_COUNT) AS TOTAL_AQI_COUNT,
    CITY,
    COUNTRY,
    YEAR,
    MONTH
FROM
    (SELECT
        EXTRACT(YEAR FROM DATE_TIME) AS YEAR,
        EXTRACT(MONTH FROM DATE_TIME) AS MONTH,
        C.COUNTRY,
        C.CITY,
        A.AIR_QUALITY_INDEX,
        COUNT(*) AS AQI_COUNT
    FROM
        AIR_POLLUTION AS A
    JOIN
        CITIES AS C
    ON
        A.LATITUDE = C.LATITUDE
        AND A.LONGITUDE = C.LONGITUDE
    WHERE
        EXTRACT(YEAR FROM DATE_TIME) = 2021
        AND EXTRACT(MONTH FROM DATE_TIME) IN (3, 4, 5)
        AND A.AIR_QUALITY_INDEX >= 4
    GROUP BY
        COUNTRY,
        CITY,
        YEAR,
        MONTH,
        A.AIR_QUALITY_INDEX) AS MAIN_QUERY
GROUP BY
    CITY,
    COUNTRY,
    YEAR,
    MONTH
ORDER BY
    MONTH, TOTAL_AQI_COUNT DESC;

100 rows affected.

[(Decimal('349'), 'Paris', 'France', 2021.0, 3.0),
 (Decimal('318'), 'Bucharest', 'Romania', 2021.0, 3.0),
 (Decimal('275'), 'Rome', 'Italy', 2021.0, 3.0),
 (Decimal('251'), 'Prague', 'Czechia', 2021.0, 3.0),
 (Decimal('226'), 'Sofia', 'Bulgaria', 2021.0, 3.0),
 (Decimal('220'), 'Ljubljana', 'Slovenia', 2021.0, 3.0),
 (Decimal('208'), 'Warsaw', 'Poland', 2021.0, 3.0),
 (Decimal('205'), 'Bern', 'Switzerland', 2021.0, 3.0),
 (Decimal('201'), 'Budapest', 'Hungary', 2021.0, 3.0),
 (Decimal('196'), 'Belgrade', 'Serbia', 2021.0, 3.0),
 (Decimal('188'), 'Vienna', 'Austria', 2021.0, 3.0),
 (Decimal('187'), 'Monaco', 'Monaco', 2021.0, 3.0),
 (Decimal('183'), 'Berlin', 'Germany', 2021.0, 3.0),
 (Decimal('153'), 'Zagreb', 'Croatia', 2021.0, 3.0),
 (Decimal('148'), 'Moscow', 'Russia', 2021.0, 3.0),
 (Decimal('139'), 'Bratislava', 'Slovakia', 2021.0, 3.0),
 (Decimal('131'), 'Skopje', 'North Macedonia', 2021.0, 3.0),
 (Decimal('119'), 'San Marino', 'San Marino', 2021.0, 3.0),
 (Decimal('106'), 'London', 'United Kingdom', 2021.0, 3.0),
 (Decimal('105'), 'Brussels', 'Belgium', 2021.0, 3.0),
 (Decimal('88'), 'Amsterdam Haag', 'Netherlands', 2021.0, 3.0),
 (Decimal('63'), 'Vaduz', 'Liechtenstein', 2021.0, 3.0),
 (Decimal('57'), 'Riga', 'Latvia', 2021.0, 3.0),
 (Decimal('55'), 'Valletta', 'Malta', 2021.0, 3.0),
 (Decimal('47'), 'Lisbon', 'Portugal', 2021.0, 3.0),
 (Decimal('46'), 'Luxembourg', 'Luxembourg', 2021.0, 3.0),
 (Decimal('38'), 'Tirana', 'Albania', 2021.0, 3.0),
 (Decimal('36'), 'Chisinau', 'Moldova', 2021.0, 3.0),
 (Decimal('34'), 'Copenhagen', 'Denmark', 2021.0, 3.0),
 (Decimal('33'), 'Athens', 'Greece', 2021.0, 3.0),
 (Decimal('31'), 'Helsinki', 'Finland', 2021.0, 3.0),
 (Decimal('29'), 'Podgorica', 'Montenegro', 2021.0, 3.0),
 (Decimal('22'), 'Kiev', 'Ukraine', 2021.0, 3.0),
 (Decimal('14'), 'Vilnius', 'Lithuania', 2021.0, 3.0),
 (Decimal('13'), 'Stockholm', 'Sweden', 2021.0, 3.0),
 (Decimal('13'), 'Tallinn', 'Estonia', 2021.0, 3.0),
 (Decimal('12'), 'Sarajevo', 'Bosnia and Herzegovina', 2021.0, 3.0),
 (Decimal('9'), 'Reykjavik', 'Iceland', 2021.0, 3.0),
 (Decimal('5'), 'Oslo', 'Norway', 2021.0, 3.0),
 (Decimal('291'), 'Paris', 'France', 2021.0, 4.0),
 (Decimal('225'), 'Valletta', 'Malta', 2021.0, 4.0),
 (Decimal('203'), 'Rome', 'Italy', 2021.0, 4.0),
 (Decimal('175'), 'Bucharest', 'Romania', 2021.0, 4.0),
 (Decimal('120'), 'Warsaw', 'Poland', 2021.0, 4.0),
 (Decimal('115'), 'Athens', 'Greece', 2021.0, 4.0),
 (Decimal('93'), 'Sofia', 'Bulgaria', 2021.0, 4.0),
 (Decimal('78'), 'Prague', 'Czechia', 2021.0, 4.0),
 (Decimal('77'), 'Brussels', 'Belgium', 2021.0, 4.0),
 (Decimal('64'), 'Ljubljana', 'Slovenia', 2021.0, 4.0),
 (Decimal('60'), 'Bern', 'Switzerland', 2021.0, 4.0),
 (Decimal('57'), 'Skopje', 'North Macedonia', 2021.0, 4.0),
 (Decimal('54'), 'Belgrade', 'Serbia', 2021.0, 4.0),
 (Decimal('50'), 'Lisbon', 'Portugal', 2021.0, 4.0),
 (Decimal('48'), 'London', 'United Kingdom', 2021.0, 4.0),
 (Decimal('46'), 'Podgorica', 'Montenegro', 2021.0, 4.0),
 (Decimal('42'), 'Tirana', 'Albania', 2021.0, 4.0),
 (Decimal('41'), 'Budapest', 'Hungary', 2021.0, 4.0),
 (Decimal('41'), 'Moscow', 'Russia', 2021.0, 4.0),
 (Decimal('28'), 'Zagreb', 'Croatia', 2021.0, 4.0),
 (Decimal('24'), 'Monaco', 'Monaco', 2021.0, 4.0),
 (Decimal('23'), 'Luxembourg', 'Luxembourg', 2021.0, 4.0),
 (Decimal('18'), 'Bratislava', 'Slovakia', 2021.0, 4.0),
 (Decimal('18'), 'Vienna', 'Austria', 2021.0, 4.0),
 (Decimal('18'), 'Vaduz', 'Liechtenstein', 2021.0, 4.0),
 (Decimal('11'), 'Berlin', 'Germany', 2021.0, 4.0),
 (Decimal('10'), 'Amsterdam Haag', 'Netherlands', 2021.0, 4.0),
 (Decimal('8'), 'Riga', 'Latvia', 2021.0, 4.0),
 (Decimal('8'), 'Sarajevo', 'Bosnia and Herzegovina', 2021.0, 4.0),
 (Decimal('7'), 'Helsinki', 'Finland', 2021.0, 4.0),
 (Decimal('6'), 'Chisinau', 'Moldova', 2021.0, 4.0),
 (Decimal('5'), 'Andorra la Vella', 'Andorra', 2021.0, 4.0),
 (Decimal('4'), 'Copenhagen', 'Denmark', 2021.0, 4.0),
 (Decimal('1'), 'Tallinn', 'Estonia', 2021.0, 4.0),
 (Decimal('1'), 'San Marino', 'San Marino', 2021.0, 4.0),
 (Decimal('177'), 'Valletta', 'Malta', 2021.0, 5.0),
 (Decimal('161'), 'Tirana', 'Albania', 2021.0, 5.0),
 (Decimal('128'), 'Athens', 'Greece', 2021.0, 5.0),
 (Decimal('121'), 'Bucharest', 'Romania', 2021.0, 5.0),
 (Decimal('99'), 'Podgorica', 'Montenegro', 2021.0, 5.0),
 (Decimal('68'), 'Paris', 'France', 2021.0, 5.0),
 (Decimal('65'), 'Rome', 'Italy', 2021.0, 5.0),
 (Decimal('46'), 'Moscow', 'Russia', 2021.0, 5.0),
 (Decimal('45'), 'Sofia', 'Bulgaria', 2021.0, 5.0),
 (Decimal('40'), 'Belgrade', 'Serbia', 2021.0, 5.0),
 (Decimal('38'), 'Warsaw', 'Poland', 2021.0, 5.0),
 (Decimal('33'), 'Skopje', 'North Macedonia', 2021.0, 5.0),
 (Decimal('27'), 'Sarajevo', 'Bosnia and Herzegovina', 2021.0, 5.0),
 (Decimal('21'), 'Chisinau', 'Moldova', 2021.0, 5.0),
 (Decimal('18'), 'Helsinki', 'Finland', 2021.0, 5.0),
 (Decimal('18'), 'Riga', 'Latvia', 2021.0, 5.0),
 (Decimal('12'), 'Prague', 'Czechia', 2021.0, 5.0),
 (Decimal('10'), 'San Marino', 'San Marino', 2021.0, 5.0),
 (Decimal('9'), 'Tallinn', 'Estonia', 2021.0, 5.0),
 (Decimal('8'), 'Budapest', 'Hungary', 2021.0, 5.0),
 (Decimal('7'), 'Zagreb', 'Croatia', 2021.0, 5.0),
 (Decimal('5'), 'Berlin', 'Germany', 2021.0, 5.0),
 (Decimal('3'), 'Vienna', 'Austria', 2021.0, 5.0),
 (Decimal('1'), 'Kiev', 'Ukraine', 2021.0, 5.0),
 (Decimal('1'), 'Stockholm', 'Sweden', 2021.0, 5.0),
 (Decimal('1'), 'Ljubljana', 'Slovenia', 2021.0, 5.0)]

In [61]:
%%sql postgresql://{db_username}:{db_password}@{db_host}:{db_port}/{db_name}

--Ranking the most polluted cities from 2022
SELECT  SUM(AQI_COUNT),
        CITY,
        COUNTRY
FROM
    (SELECT EXTRACT(YEAR FROM DATE_TIME) AS YEAR,
        C.COUNTRY,
        C.CITY,
        COUNT(A.AIR_QUALITY_INDEX) AS AQI_COUNT
FROM AIR_POLLUTION AS A
JOIN CITIES AS C ON A.LATITUDE = C.LATITUDE
        AND A.LONGITUDE = C.LONGITUDE
WHERE EXTRACT(YEAR FROM DATE_TIME) = 2022
        AND A.AIR_QUALITY_INDEX = 5
GROUP BY COUNTRY,
         CITY,
         AIR_QUALITY_INDEX,
         DATE_TIME
ORDER BY AIR_QUALITY_INDEX DESC) AS MAIN
GROUP BY CITY, COUNTRY
ORDER BY SUM DESC;

37 rows affected.

[(Decimal('1251'), 'Paris', 'France'),
 (Decimal('1085'), 'Bucharest', 'Romania'),
 (Decimal('1032'), 'Valletta', 'Malta'),
 (Decimal('669'), 'Rome', 'Italy'),
 (Decimal('517'), 'Warsaw', 'Poland'),
 (Decimal('497'), 'Skopje', 'North Macedonia'),
 (Decimal('378'), 'Prague', 'Czechia'),
 (Decimal('347'), 'Sofia', 'Bulgaria'),
 (Decimal('322'), 'Ljubljana', 'Slovenia'),
 (Decimal('307'), 'Zagreb', 'Croatia'),
 (Decimal('252'), 'Athens', 'Greece'),
 (Decimal('242'), 'Budapest', 'Hungary'),
 (Decimal('236'), 'Belgrade', 'Serbia'),
 (Decimal('218'), 'Helsinki', 'Finland'),
 (Decimal('190'), 'Moscow', 'Russia'),
 (Decimal('153'), 'Riga', 'Latvia'),
 (Decimal('149'), 'Bern', 'Switzerland'),
 (Decimal('102'), 'Vienna', 'Austria'),
 (Decimal('98'), 'Lisbon', 'Portugal'),
 (Decimal('87'), 'San Marino', 'San Marino'),
 (Decimal('73'), 'Tallinn', 'Estonia'),
 (Decimal('65'), 'Brussels', 'Belgium'),
 (Decimal('48'), 'London', 'United Kingdom'),
 (Decimal('46'), 'Berlin', 'Germany'),
 (Decimal('41'), 'Amsterdam Haag', 'Netherlands'),
 (Decimal('41'), 'Copenhagen', 'Denmark'),
 (Decimal('35'), 'Vaduz', 'Liechtenstein'),
 (Decimal('30'), 'Sarajevo', 'Bosnia and Herzegovina'),
 (Decimal('27'), 'Monaco', 'Monaco'),
 (Decimal('26'), 'Tirana', 'Albania'),
 (Decimal('23'), 'Luxembourg', 'Luxembourg'),
 (Decimal('19'), 'Bratislava', 'Slovakia'),
 (Decimal('15'), 'Chisinau', 'Moldova'),
 (Decimal('12'), 'Andorra la Vella', 'Andorra'),
 (Decimal('11'), 'Vilnius', 'Lithuania'),
 (Decimal('11'), 'Kiev', 'Ukraine'),
 (Decimal('6'), 'Podgorica', 'Montenegro')]

In [63]:
%%sql postgresql://{db_username}:{db_password}@{db_host}:{db_port}/{db_name}

-- Ranking cities with the least air pollution according to the air quality index
SELECT  SUM(AQI_COUNT),
        CITY,
        COUNTRY
FROM
    (SELECT EXTRACT(YEAR FROM DATE_TIME) AS YEAR,
        C.COUNTRY,
        C.CITY,
        COUNT(A.AIR_QUALITY_INDEX) AS AQI_COUNT
FROM AIR_POLLUTION AS A
JOIN CITIES AS C ON A.LATITUDE = C.LATITUDE
        AND A.LONGITUDE = C.LONGITUDE
WHERE EXTRACT(YEAR FROM DATE_TIME) = 2021
        AND A.AIR_QUALITY_INDEX < 2
GROUP BY COUNTRY,
         CITY,
         AIR_QUALITY_INDEX,
         DATE_TIME
ORDER BY AIR_QUALITY_INDEX DESC) AS MAIN
GROUP BY CITY, COUNTRY
ORDER BY SUM DESC;

40 rows affected.

[(Decimal('7535'), 'Reykjavik', 'Iceland'),
 (Decimal('7355'), 'Oslo', 'Norway'),
 (Decimal('7159'), 'Stockholm', 'Sweden'),
 (Decimal('6885'), 'Andorra la Vella', 'Andorra'),
 (Decimal('6656'), 'Tallinn', 'Estonia'),
 (Decimal('6575'), 'Vilnius', 'Lithuania'),
 (Decimal('6362'), 'Kiev', 'Ukraine'),
 (Decimal('6323'), 'Helsinki', 'Finland'),
 (Decimal('6033'), 'Luxembourg', 'Luxembourg'),
 (Decimal('5951'), 'London', 'United Kingdom'),
 (Decimal('5927'), 'Riga', 'Latvia'),
 (Decimal('5823'), 'Copenhagen', 'Denmark'),
 (Decimal('5769'), 'Chisinau', 'Moldova'),
 (Decimal('5430'), 'Vaduz', 'Liechtenstein'),
 (Decimal('5382'), 'Amsterdam Haag', 'Netherlands'),
 (Decimal('5165'), 'Brussels', 'Belgium'),
 (Decimal('5068'), 'Berlin', 'Germany'),
 (Decimal('4998'), 'Moscow', 'Russia'),
 (Decimal('4902'), 'Sarajevo', 'Bosnia and Herzegovina'),
 (Decimal('4646'), 'Bratislava', 'Slovakia'),
 (Decimal('4547'), 'Lisbon', 'Portugal'),
 (Decimal('4491'), 'Bern', 'Switzerland'),
 (Decimal('4370'), 'Vienna', 'Austria'),
 (Decimal('4080'), 'Prague', 'Czechia'),
 (Decimal('3651'), 'Warsaw', 'Poland'),
 (Decimal('3629'), 'Monaco', 'Monaco'),
 (Decimal('3580'), 'Budapest', 'Hungary'),
 (Decimal('3507'), 'Belgrade', 'Serbia'),
 (Decimal('3474'), 'San Marino', 'San Marino'),
 (Decimal('3325'), 'Zagreb', 'Croatia'),
 (Decimal('3299'), 'Podgorica', 'Montenegro'),
 (Decimal('3276'), 'Tirana', 'Albania'),
 (Decimal('3265'), 'Sofia', 'Bulgaria'),
 (Decimal('3200'), 'Paris', 'France'),
 (Decimal('2935'), 'Ljubljana', 'Slovenia'),
 (Decimal('2611'), 'Skopje', 'North Macedonia'),
 (Decimal('2553'), 'Bucharest', 'Romania'),
 (Decimal('2361'), 'Athens', 'Greece'),
 (Decimal('2338'), 'Rome', 'Italy'),
 (Decimal('688'), 'Valletta', 'Malta')]

In [64]:
%%sql postgresql://{db_username}:{db_password}@{db_host}:{db_port}/{db_name}

--Ranking the cities by yearly avarage particulate matter (pm2.5)
SELECT
        COUNTRY,
        CITY,
        AVG(AVG_PM2_5) AS AVARAGE_PM2_5
FROM (
SELECT  EXTRACT(YEAR FROM DATE_TIME) AS YEAR,
        C.COUNTRY,
        C.CITY,
        AVG(A.PM2_5) AS AVG_PM2_5
FROM AIR_POLLUTION AS A
JOIN CITIES AS C ON A.LATITUDE = C.LATITUDE
        AND A.LONGITUDE = C.LONGITUDE
WHERE EXTRACT(YEAR FROM DATE_TIME) = 2021
GROUP BY COUNTRY,
         CITY,
         PM2_5,
         DATE_TIME
) AS MAIN_QUERY
GROUP BY COUNTRY,
         CITY
ORDER BY AVG(AVG_PM2_5) DESC

40 rows affected.

[('France', 'Paris', Decimal('31.69398695054945054945')),
 ('Romania', 'Bucharest', Decimal('23.62141254578754578755')),
 ('Malta', 'Valletta', Decimal('21.33238553113553113553')),
 ('Italy', 'Rome', Decimal('19.67071314102564102564')),
 ('Poland', 'Warsaw', Decimal('18.03744963369963369963')),
 ('North Macedonia', 'Skopje', Decimal('16.28143086080586080586')),
 ('Slovenia', 'Ljubljana', Decimal('15.75704441391941391941')),
 ('Bulgaria', 'Sofia', Decimal('15.33139537545787545788')),
 ('Greece', 'Athens', Decimal('14.82494047619047619048')),
 ('Czechia', 'Prague', Decimal('14.75094551282051282051')),
 ('Croatia', 'Zagreb', Decimal('14.43726991758241758242')),
 ('Serbia', 'Belgrade', Decimal('14.32287202380952380952')),
 ('Hungary', 'Budapest', Decimal('14.04509271978021978022')),
 ('Albania', 'Tirana', Decimal('12.54778617216117216117')),
 ('Austria', 'Vienna', Decimal('11.55959821428571428571')),
 ('Montenegro', 'Podgorica', Decimal('11.31930631868131868132')),
 ('Russia', 'Moscow', Decimal('11.10497481684981684982')),
 ('Switzerland', 'Bern', Decimal('10.65298992673992673993')),
 ('San Marino', 'San Marino', Decimal('10.58594322344322344322')),
 ('Monaco', 'Monaco', Decimal('10.26355769230769230769')),
 ('Germany', 'Berlin', Decimal('9.53000801282051282051')),
 ('Belgium', 'Brussels', Decimal('8.84502976190476190476')),
 ('Slovakia', 'Bratislava', Decimal('8.77257669413919413919')),
 ('Bosnia and Herzegovina', 'Sarajevo', Decimal('8.15806433150183150183')),
 ('Latvia', 'Riga', Decimal('8.14556662087912087912')),
 ('Finland', 'Helsinki', Decimal('8.04773466117216117216')),
 ('Liechtenstein', 'Vaduz', Decimal('7.59092376373626373626')),
 ('Moldova', 'Chisinau', Decimal('7.24148809523809523810')),
 ('Portugal', 'Lisbon', Decimal('7.14389079670329670330')),
 ('United Kingdom', 'London', Decimal('6.65393429487179487179')),
 ('Luxembourg', 'Luxembourg', Decimal('6.54804601648351648352')),
 ('Ukraine', 'Kiev', Decimal('6.54151442307692307692')),
 ('Netherlands', 'Amsterdam Haag', Decimal('6.49296703296703296703')),
 ('Lithuania', 'Vilnius', Decimal('6.33636790293040293040')),
 ('Denmark', 'Copenhagen', Decimal('5.92070970695970695971')),
 ('Estonia', 'Tallinn', Decimal('5.85334134615384615385')),
 ('Andorra', 'Andorra la Vella', Decimal('4.42045558608058608059')),
 ('Norway', 'Oslo', Decimal('3.73464743589743589744')),
 ('Sweden', 'Stockholm', Decimal('3.69286515567765567766')),
 ('Iceland', 'Reykjavik', Decimal('1.61212683150183150183'))]